### ISSUE TITLE
Support Ganache CHAIN_ID 1337

### ISSUE THREAD

**Issue by fragosti** [0xProject/0x-event-pipeline#21]
It would be nice to be able to support ganache in testing environments, such as for the 0x-api.

**Comment by alexkroeger** [comment]
Do you know what could serve for these values:

https://github.com/0xProject/0x-event-pipeline/blob/6fead5b798771b1020695c27acc8b0d8bc6a281b/src/config.ts#L25

https://github.com/0xProject/0x-event-pipeline/blob/6fead5b798771b1020695c27acc8b0d8bc6a281b/src/config.ts#L33
